//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APA
{
    using System;
    using System.Collections.Generic;
    
    public partial class DivisionRep
    {
        public int DivRepDivisionNumber { get; set; }
        public string DivRepFirstName { get; set; }
        public string DivRepLastName { get; set; }
        public string DivRepPhone { get; set; }
        public string DivRepEmail { get; set; }
        public string DivRepPassword { get; set; }
    }
}
