//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerNumber { get; set; }
        public string PlayerFirstName { get; set; }
        public string PlayerLastName { get; set; }
        public int SkillLevel { get; set; }
        public int MatchesPlayed { get; set; }
        public int PlayerDivNumber { get; set; }
        public int PlayerTeamNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PlayerPhone { get; set; }
        public string PlayerEmail { get; set; }
        public string Status { get; set; }
        public string CardNumber { get; set; }
        public string CardExpDate { get; set; }
        public string CVC { get; set; }
        public string PlayerPassword { get; set; }
    }
}
