//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamNumber { get; set; }
        public string TeamName { get; set; }
        public string TeamLocation { get; set; }
        public int TeamPoints { get; set; }
    }
}
